services:
  jellyfin-movie-picker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BUN_RUNTIME=1
    restart: unless-stopped
